import type { ProcessedAsset, SampleMediaItem } from '../src/types/pipeline.js';

export const SAMPLE_PRESETS: SampleMediaItem[] = [
  {
    id: 'sample-sneaker',
    name: 'Pro-Aero Runner Sneaker',
    category: 'Footwear & Apparel',
    description: 'Raw product shot with studio floor texture. Tests background removal, Amazon marketplace 1:1 framing, and color extraction.',
    thumbnailUrl: '/src/assets/images/sample_sneaker_raw_1790864772737.jpg',
    aspectRatio: '4:3',
    suggestedTags: ['sneaker', 'footwear', 'running', 'athletic', 'sportswear', 'product'],
  },
  {
    id: 'sample-portrait',
    name: 'Executive Founder Portrait',
    category: 'Corporate & Editorial',
    description: 'Corporate headshot with modern office backdrop. Tests facial gravity detection (g_auto:face) and 4:5 vertical social cropping.',
    thumbnailUrl: '/src/assets/images/sample_portrait_raw_1790864784966.jpg',
    aspectRatio: '4:3',
    suggestedTags: ['portrait', 'headshot', 'executive', 'leadership', 'professional', 'people'],
  },
  {
    id: 'sample-smartwatch',
    name: 'Chronos Luxe Smartwatch',
    category: 'Consumer Electronics',
    description: 'High-contrast angled wearable photo. Tests dynamic contrast enhancement (e_enhance), f_auto format compression, and mobile DPR scaling.',
    thumbnailUrl: '/src/assets/images/sample_smartwatch_raw_1790864796471.jpg',
    aspectRatio: '4:3',
    suggestedTags: ['smartwatch', 'wearable', 'luxury', 'technology', 'gadget', 'minimalist'],
  },
  {
    id: 'sample-camera',
    name: 'AeroOptic Rangefinder Camera',
    category: 'Optics & Photography',
    description: 'Artisanal desk still life with shallow depth of field. Tests subject isolation, 16:9 cinematic framing, and web optimization.',
    thumbnailUrl: '/src/assets/images/sample_camera_raw_1790864809516.jpg',
    aspectRatio: '4:3',
    suggestedTags: ['camera', 'vintage', 'rangefinder', 'optics', 'photography', 'artisan'],
  },
];

// Initial seeded processed assets for the Asset Library
export const INITIAL_PROCESSED_ASSETS: ProcessedAsset[] = [
  {
    id: 'asset_pro_runner_sneaker_seeded',
    publicId: 'reframe-ai/pro_runner_sneaker_01',
    cloudName: 'demo',
    originalUrl: '/src/assets/images/sample_sneaker_raw_1790864772737.jpg',
    format: 'jpg',
    originalWidth: 2048,
    originalHeight: 1536,
    originalBytes: 1845000,
    optimizedBytes: 284000,
    createdAt: '2026-10-01T06:30:00.000Z',
    intelligence: {
      detectedSubject: 'Athletic Running Sneaker',
      category: 'Footwear & Apparel',
      subcategory: 'Performance Running',
      tags: ['sneaker', 'footwear', 'running', 'teal', 'sportswear', 'cushion'],
      contentSafety: 'Safe',
      safetyDetails: {
        adult: 'Very Unlikely',
        violence: 'Very Unlikely',
        medical: 'Very Unlikely',
        racy: 'Very Unlikely',
      },
      composition: {
        subjectPlacement: 'Centered',
        backgroundComplexity: 'Distracting',
        recommendedCrop: '1:1 Square Pad / White Background',
        aspectRatio: '4:3',
        contrast: 'High',
        lighting: 'Studio Diffused',
      },
      dominantColors: [
        { hex: '#0D9488', name: 'Vibrant Teal', percentage: 38 },
        { hex: '#F97316', name: 'Solar Orange', percentage: 24 },
        { hex: '#1E293B', name: 'Dark Slate', percentage: 22 },
        { hex: '#F8FAFC', name: 'Off White', percentage: 16 },
      ],
    },
    readiness: {
      overallScore: 94,
      checks: [
        {
          id: 'ai-analysis',
          label: 'AI Analysis & Subject Detection',
          passed: true,
          score: 20,
          details: 'Primary subject identified: "Athletic Running Sneaker" with 98.4% confidence.',
        },
        {
          id: 'metadata-enrichment',
          label: 'Metadata & Semantic Tags',
          passed: true,
          score: 20,
          details: '6 high-intent e-commerce discovery tags attached to asset record.',
        },
        {
          id: 'content-safety',
          label: 'Content Safety & Compliance',
          passed: true,
          score: 20,
          details: 'Verified 100% compliant with commercial advertising standards.',
        },
        {
          id: 'composition-resolution',
          label: 'Composition & Resolution Quality',
          passed: true,
          score: 18,
          details: '2048×1536px studio canvas. Minor background floor texture flagged for cutout.',
        },
        {
          id: 'delivery-optimization',
          label: 'Delivery Optimization (f_auto / q_auto)',
          passed: true,
          score: 20,
          details: 'Cloudinary perceptual compression enabled (84.6% bandwidth saving via WebP/AVIF).',
        },
      ],
      recommendations: [
        'Deploy the 1:1 Marketplace White Pad variant for Shopify and Amazon product cards.',
        'Use the Cutout Isolated PNG for dynamic marketing overlays.',
      ],
    },
    variants: [
      {
        id: 'website-16-9',
        name: 'Website Banner',
        target: 'Website',
        aspectRatio: '16:9',
        aspectRatioLabel: '16:9 Landscape',
        width: 1920,
        height: 1080,
        transformationString: 'c_fill,ar_16:9,g_auto,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/c_fill,ar_16:9,g_auto,f_auto,q_auto/shoes.jpg',
        description: 'Optimized for web headers and desktop viewports with content-aware subject centering.',
        gravity: 'g_auto',
        format: 'f_auto',
        quality: 'q_auto',
        estimatedBytes: 245000,
      },
      {
        id: 'social-4-5',
        name: 'Social Media Feed',
        target: 'Social',
        aspectRatio: '4:5',
        aspectRatioLabel: '4:5 Portrait',
        width: 1080,
        height: 1350,
        transformationString: 'c_fill,ar_4:5,g_auto:subject,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/c_fill,ar_4:5,g_auto:subject,f_auto,q_auto/shoes.jpg',
        description: 'Ideal for Instagram and mobile vertical feeds with subject priority cropping.',
        gravity: 'g_auto:subject',
        format: 'f_auto',
        quality: 'q_auto',
        estimatedBytes: 195000,
      },
      {
        id: 'marketplace-1-1',
        name: 'Marketplace Product',
        target: 'Marketplace',
        aspectRatio: '1:1',
        aspectRatioLabel: '1:1 Square',
        width: 1200,
        height: 1200,
        transformationString: 'c_pad,ar_1:1,b_white,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/c_pad,ar_1:1,b_white,f_auto,q_auto/shoes.jpg',
        description: 'Standards-compliant square aspect ratio with pure white padding for Amazon and Google Shopping.',
        gravity: 'g_center',
        format: 'f_auto',
        quality: 'q_auto',
        estimatedBytes: 165000,
      },
      {
        id: 'mobile-optimized',
        name: 'Mobile App Asset',
        target: 'Mobile',
        aspectRatio: 'Auto',
        aspectRatioLabel: 'Responsive Retina',
        width: 750,
        height: 750,
        transformationString: 'w_750,dpr_2.0,c_scale,f_auto,q_auto:eco',
        url: 'https://res.cloudinary.com/demo/image/upload/w_750,dpr_2.0,c_scale,f_auto,q_auto:eco/shoes.jpg',
        description: 'Ultra-lightweight high-DPI asset for iOS/Android apps balancing sharpness and cellular bandwidth.',
        gravity: 'g_auto',
        format: 'f_auto',
        quality: 'q_auto:eco',
        estimatedBytes: 110000,
      },
      {
        id: 'cutout-isolated',
        name: 'Isolated Cutout',
        target: 'Cutout',
        aspectRatio: 'Original',
        aspectRatioLabel: 'Transparent PNG',
        width: 1600,
        height: 1200,
        transformationString: 'e_background_removal,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/e_background_removal,f_auto,q_auto/shoes.png',
        description: 'Automatic AI background removal isolating foreground subject on transparent alpha canvas.',
        gravity: 'g_auto',
        format: 'png',
        quality: 'q_auto',
        estimatedBytes: 320000,
      },
      {
        id: 'enhanced-studio',
        name: 'Studio Color Balanced',
        target: 'Enhanced',
        aspectRatio: 'Original',
        aspectRatioLabel: 'Perceptual Enhance',
        width: 1920,
        height: 1280,
        transformationString: 'e_enhance,e_improve,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/e_enhance,e_improve,f_auto,q_auto/shoes.jpg',
        description: 'AI perceptual clarity, micro-contrast enhancement, and dynamic color temperature balancing.',
        gravity: 'g_auto',
        format: 'f_auto',
        quality: 'q_auto',
        estimatedBytes: 210000,
      },
    ],
    changesApplied: [
      {
        title: 'AI Analyzed & Classified',
        description: 'Identified athletic shoe subject and extracted palette featuring Teal (#0D9488) and Solar Orange.',
        active: true,
      },
      {
        title: 'Semantic Tags Injected',
        description: 'Stored 6 structured tags for Search API discovery and automated categorization.',
        active: true,
      },
      {
        title: 'Background Processed',
        description: 'Detected textured floor surface; generated clean white padding and transparent cutout variants.',
        active: true,
      },
      {
        title: 'Crop & Aspect Ratio Optimized',
        description: 'Preserved shoe profile curvature across 16:9, 4:5, and 1:1 using content-aware auto gravity.',
        active: true,
      },
      {
        title: 'Delivery Stream Optimized',
        description: 'Applied f_auto and q_auto cutting payload from 1.84MB down to ~284KB without perceptual quality loss.',
        active: true,
      },
    ],
    mediaPassport: {
      assetId: 'PASSPORT-SHOE-0981',
      publicId: 'reframe-ai/pro_runner_sneaker_01',
      type: 'image/jpeg',
      cloudName: 'demo',
      cdnProtocol: 'HTTPS (Fastly / Cloudflare HTTP/3 Global Edge)',
      shaChecksum: '7fa0218b284e3a479261a8dc4e929fae8812c75a',
      tags: ['sneaker', 'footwear', 'running', 'athletic', 'sportswear'],
      processingPipeline: [
        'cloudinary:upload:v2',
        'gemini:multimodal_understand',
        'cloudinary:c_fill_g_auto',
        'cloudinary:e_background_removal',
        'cloudinary:delivery:f_auto_q_auto',
      ],
      destinations: ['Website (16:9)', 'Social (4:5)', 'Marketplace (1:1)', 'Mobile (Retina)', 'Cutout (PNG)'],
      status: 'Ready',
    },
  },
  {
    id: 'asset_founder_portrait_seeded',
    publicId: 'reframe-ai/founder_portrait_02',
    cloudName: 'demo',
    originalUrl: '/src/assets/images/sample_portrait_raw_1790864784966.jpg',
    format: 'jpg',
    originalWidth: 1920,
    originalHeight: 1440,
    originalBytes: 1520000,
    optimizedBytes: 215000,
    createdAt: '2026-10-01T07:05:00.000Z',
    intelligence: {
      detectedSubject: 'Executive Professional Portrait',
      category: 'Corporate & Editorial',
      subcategory: 'Leadership Headshot',
      tags: ['portrait', 'headshot', 'executive', 'leadership', 'professional', 'corporate'],
      contentSafety: 'Safe',
      safetyDetails: {
        adult: 'Very Unlikely',
        violence: 'Very Unlikely',
        medical: 'Very Unlikely',
        racy: 'Very Unlikely',
      },
      composition: {
        subjectPlacement: 'Centered',
        backgroundComplexity: 'Moderate',
        recommendedCrop: '4:5 Vertical Social / 1:1 Avatar',
        aspectRatio: '4:3',
        contrast: 'Medium',
        lighting: 'Natural Ambient Window Light',
      },
      dominantColors: [
        { hex: '#1E293B', name: 'Navy Blazer', percentage: 44 },
        { hex: '#E2E8F0', name: 'Ambient Slate', percentage: 32 },
        { hex: '#F8FAFC', name: 'Clean White', percentage: 24 },
      ],
    },
    readiness: {
      overallScore: 96,
      checks: [
        {
          id: 'ai-analysis',
          label: 'AI Analysis & Subject Detection',
          passed: true,
          score: 20,
          details: 'Human face & subject detected with facial gravity confidence 99.2%.',
        },
        {
          id: 'metadata-enrichment',
          label: 'Metadata & Semantic Tags',
          passed: true,
          score: 20,
          details: 'Indexed under Corporate & Editorial taxonomy with 6 professional tags.',
        },
        {
          id: 'content-safety',
          label: 'Content Safety & Compliance',
          passed: true,
          score: 20,
          details: 'Passed all moderation checks. Safe for executive team directories and press kits.',
        },
        {
          id: 'composition-resolution',
          label: 'Composition & Resolution Quality',
          passed: true,
          score: 20,
          details: '1920×1440px canvas. Natural focal depth with clear eye-line positioning.',
        },
        {
          id: 'delivery-optimization',
          label: 'Delivery Optimization (f_auto / q_auto)',
          passed: true,
          score: 20,
          details: 'Skin tone preserving q_auto compression with modern AVIF delivery.',
        },
      ],
      recommendations: [
        'Deploy the 4:5 Social Media variant for LinkedIn and executive profiles.',
        'Use the Website 16:9 crop for team bios and keynote event banners.',
      ],
    },
    variants: [
      {
        id: 'website-16-9',
        name: 'Website Banner',
        target: 'Website',
        aspectRatio: '16:9',
        aspectRatioLabel: '16:9 Landscape',
        width: 1920,
        height: 1080,
        transformationString: 'c_fill,ar_16:9,g_auto:face,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/c_fill,ar_16:9,g_auto:face,f_auto,q_auto/face_top.jpg',
        description: 'Hero header framing prioritizing facial alignment.',
        gravity: 'g_auto:face',
        format: 'f_auto',
        quality: 'q_auto',
        estimatedBytes: 230000,
      },
      {
        id: 'social-4-5',
        name: 'Social Media Feed',
        target: 'Social',
        aspectRatio: '4:5',
        aspectRatioLabel: '4:5 Portrait',
        width: 1080,
        height: 1350,
        transformationString: 'c_fill,ar_4:5,g_auto:face,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/c_fill,ar_4:5,g_auto:face,f_auto,q_auto/face_top.jpg',
        description: 'Optimized vertical portrait with face auto-centering.',
        gravity: 'g_auto:face',
        format: 'f_auto',
        quality: 'q_auto',
        estimatedBytes: 185000,
      },
      {
        id: 'marketplace-1-1',
        name: 'Directory Avatar',
        target: 'Marketplace',
        aspectRatio: '1:1',
        aspectRatioLabel: '1:1 Square',
        width: 1200,
        height: 1200,
        transformationString: 'c_thumb,g_face,w_1200,h_1200,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/c_thumb,g_face,w_1200,h_1200,f_auto,q_auto/face_top.jpg',
        description: 'Standardized square profile thumbnail using Cloudinary face detection.',
        gravity: 'g_face',
        format: 'f_auto',
        quality: 'q_auto',
        estimatedBytes: 155000,
      },
      {
        id: 'mobile-optimized',
        name: 'Mobile App Asset',
        target: 'Mobile',
        aspectRatio: 'Auto',
        aspectRatioLabel: 'Responsive Retina',
        width: 750,
        height: 750,
        transformationString: 'w_750,dpr_2.0,c_scale,f_auto,q_auto:eco',
        url: 'https://res.cloudinary.com/demo/image/upload/w_750,dpr_2.0,c_scale,f_auto,q_auto:eco/face_top.jpg',
        description: 'Retina ready mobile avatar stream.',
        gravity: 'g_auto',
        format: 'f_auto',
        quality: 'q_auto:eco',
        estimatedBytes: 98000,
      },
      {
        id: 'cutout-isolated',
        name: 'Isolated Cutout',
        target: 'Cutout',
        aspectRatio: 'Original',
        aspectRatioLabel: 'Transparent PNG',
        width: 1600,
        height: 1200,
        transformationString: 'e_background_removal,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/e_background_removal,f_auto,q_auto/face_top.png',
        description: 'Clean silhouette cutout removing background office elements.',
        gravity: 'g_auto',
        format: 'png',
        quality: 'q_auto',
        estimatedBytes: 280000,
      },
      {
        id: 'enhanced-studio',
        name: 'Studio Color Balanced',
        target: 'Enhanced',
        aspectRatio: 'Original',
        aspectRatioLabel: 'Perceptual Enhance',
        width: 1920,
        height: 1280,
        transformationString: 'e_enhance,e_improve,f_auto,q_auto',
        url: 'https://res.cloudinary.com/demo/image/upload/e_enhance,e_improve,f_auto,q_auto/face_top.jpg',
        description: 'Skin tone refinement and background depth balancing.',
        gravity: 'g_auto',
        format: 'f_auto',
        quality: 'q_auto',
        estimatedBytes: 205000,
      },
    ],
    changesApplied: [
      {
        title: 'AI Analyzed & Classified',
        description: 'Identified human portrait; calculated optimal rule-of-thirds face bounding box.',
        active: true,
      },
      {
        title: 'Semantic Tags Injected',
        description: 'Tagged with executive, leadership, and corporate metadata.',
        active: true,
      },
      {
        title: 'Background Processed',
        description: 'Office background soft-focus preserved for editorial; transparent cutout generated for badges.',
        active: true,
      },
      {
        title: 'Crop & Aspect Ratio Optimized',
        description: 'Applied g_auto:face to prevent awkward forehead or collar clipping in 16:9 and 1:1 crops.',
        active: true,
      },
      {
        title: 'Delivery Stream Optimized',
        description: 'AVIF format selected dynamically for supporting browsers with 85.8% size reduction.',
        active: true,
      },
    ],
    mediaPassport: {
      assetId: 'PASSPORT-PORT-0412',
      publicId: 'reframe-ai/founder_portrait_02',
      type: 'image/jpeg',
      cloudName: 'demo',
      cdnProtocol: 'HTTPS (Fastly / Cloudflare HTTP/3 Global Edge)',
      shaChecksum: '3a18e00192e48fa2981bc92e01a88b172a8190de',
      tags: ['portrait', 'headshot', 'executive', 'leadership', 'professional'],
      processingPipeline: [
        'cloudinary:upload:v2',
        'gemini:multimodal_understand',
        'cloudinary:c_fill_g_auto:face',
        'cloudinary:e_background_removal',
        'cloudinary:delivery:f_auto_q_auto',
      ],
      destinations: ['Website (16:9)', 'Social (4:5)', 'Marketplace (1:1)', 'Mobile (Retina)', 'Cutout (PNG)'],
      status: 'Ready',
    },
  },
];
